# Generated by Django 3.0.4 on 2020-03-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20200319_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70)),
                ('reseña', models.CharField(max_length=300)),
                ('libro', models.CharField(max_length=200)),
            ],
        ),
    ]
