# Generated by Django 3.0.4 on 2020-03-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_reseña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
    ]
