# Generated by Django 3.0.4 on 2020-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20200324_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='usuario',
            field=models.CharField(max_length=70),
        ),
    ]
