# Generated by Django 3.0.4 on 2020-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20200324_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='registrado',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='registrado',
            name='usuario',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
