# Generated by Django 3.0.4 on 2020-03-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20200325_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('lanzamiento', models.IntegerField()),
            ],
        ),
    ]
