# Generated by Django 3.0.4 on 2020-03-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
