# Generated by Django 3.0.4 on 2020-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_delete_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
