# Generated by Django 3.0.4 on 2020-03-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_delete_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70)),
                ('calificacion', models.IntegerField()),
                ('resena', models.CharField(max_length=600)),
                ('libro_titulo', models.CharField(max_length=70)),
            ],
        ),
    ]
