# Generated by Django 3.0.4 on 2020-04-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='resena',
            field=models.CharField(max_length=4000),
        ),
    ]
