# Generated by Django 3.0.4 on 2020-05-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_auto_20200530_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
